// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"gorm.io/gorm"
	"server/internal/adapter/db/repository"
	"server/internal/interface/api"
	"server/internal/useCase/query"
)

// Injectors from wire.go:

func WireStudentApi(db *gorm.DB) api.Student {
	studentRepository := repository.ProvideStudentRepository(db)
	getAllStudents := query.ProvideGetAllStudents(studentRepository)
	student := api.ProvideStudent(getAllStudents)
	return student
}

func WireClassApi(db *gorm.DB) api.Class {
	classRepository := repository.ProvideClassRepository(db)
	getAllClasses := query.ProvideGetAllClasses(classRepository)
	class := api.ProvideClass(getAllClasses)
	return class
}
